language: node_js

addons:
  sonarcloud:
    organization: "memory-cloud"

node_js:
- '8'

install:
- npm install

cache:
  directories:
  - node_modules

script:
- sonar-scanner -Dsonar.projectKey=server -Dsonar.organization=memory-cloud -Dsonar.sources=./src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
- eslint *.js --debug
- npm run build