version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo:3.4.10
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - "6379:6379"